// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// natural_spline_4d
Rcpp::RObject natural_spline_4d(std::string infile, const std::vector<int>& t_interpolate, bool edge_nn, std::string outfile, bool internal);
RcppExport SEXP _BrainGnomes_natural_spline_4d(SEXP infileSEXP, SEXP t_interpolateSEXP, SEXP edge_nnSEXP, SEXP outfileSEXP, SEXP internalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type infile(infileSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type t_interpolate(t_interpolateSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_nn(edge_nnSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< bool >::type internal(internalSEXP);
    rcpp_result_gen = Rcpp::wrap(natural_spline_4d(infile, t_interpolate, edge_nn, outfile, internal));
    return rcpp_result_gen;
END_RCPP
}
// natural_spline_interp
NumericVector natural_spline_interp(NumericVector x, NumericVector y, NumericVector xout);
RcppExport SEXP _BrainGnomes_natural_spline_interp(SEXP xSEXP, SEXP ySEXP, SEXP xoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    rcpp_result_gen = Rcpp::wrap(natural_spline_interp(x, y, xout));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BrainGnomes_natural_spline_4d", (DL_FUNC) &_BrainGnomes_natural_spline_4d, 5},
    {"_BrainGnomes_natural_spline_interp", (DL_FUNC) &_BrainGnomes_natural_spline_interp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BrainGnomes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
