# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolate fMRI Time Series with Cubic Splines in a NIfTI File
#'
#' This function performs voxelwise natural cubic spline interpolation over the time
#' dimension of a 4D NIfTI image. Timepoints to interpolate are specified, and interpolation
#' is applied independently to each voxel's time series.
#'
#' The function reads the NIfTI image from disk, performs interpolation in memory,
#' and optionally writes the result back to a new NIfTI file.
#'
#' @name natural_spline_4d
#' @param infile Character string. Path to the input 4D NIfTI file (e.g., BOLD fMRI data).
#' @param t_interpolate Integer vector (1-based). Specifies the timepoints (TRs) to interpolate.
#'        Timepoints outside the valid range [1, T] are ignored with a warning.
#' @param edge_nn Logical. If \code{TRUE}, extrapolated values at the edges of the time series
#'        are filled in using nearest-neighbor extrapolation instead of cubic splines.
#' @param outfile Character string (optional). If provided, the interpolated image will
#'        be written to this path. If omitted, the result is returned but not saved.
#' @param internal Logical. If FALSE (the default), an array of class "niftiImage", containing
#'        the image pixel or voxel values, will be returned. If TRUE, the return value will be
#'        an object of class "internalImage", which contains only minimal metadata about the image.
#'        Either way, the return value has an attribute which points to a C data structure
#'        containing the full image. Cf. `RNifti::readNifti`
#'
#' @return A \code{niftiImage} object with the same dimensions and metadata as the input,
#'         with interpolated values inserted at the specified timepoints.
#'
#' @details The interpolation is voxelwise and assumes column-major order. If a voxel time series
#' has fewer than three valid (non-interpolated) timepoints, or is constant across time, it is skipped.
#' Linear extrapolation is used for timepoints outside the valid range if \code{edge_nn = FALSE}, matching
#' R's `splinefun` approach with natural splines. If \code{edge_nn = TRUE}, nearest-neighbor extrapolation
#' is used for interpolation timepoints at the beginning or end of the timeseries, potentially reducing
#' extreme values in extrapolation.
#'
#' This implementation uses RNifti’s C++ API (\code{NiftiImage}, \code{NiftiImageData}) for efficient
#' memory access and file handling, allowing the function to operate directly on NIfTI files.
#'
#' @examples
#' \dontrun{
#' out_img <- natural_spline_4d(
#'   infile = "bold.nii.gz",
#'   t_interpolate = 91:95,
#'   outfile = "bold_interpolated.nii.gz",
#'   edge_nn = TRUE
#' )
#' }
#' @import RNifti
#' @export
NULL

natural_spline_4d <- function(infile, t_interpolate, edge_nn = FALSE, outfile = "", internal = FALSE) {
    .Call(`_BrainGnomes_natural_spline_4d`, infile, t_interpolate, edge_nn, outfile, internal)
}

#' Cubic spline interpolation with natural spline and linear extrapolation
#' 
#' @name natural_spline_interp
#' @description Performs natural cubic spline interpolation for given input values.
#' This function takes known data points `(x, y)` and evaluates the cubic spline
#' interpolation at specified output points `xout`. It uses a natural spline
#' formulation with zero second derivatives at the endpoints.
#'
#' @param x A numeric vector of strictly increasing x-values (time or position).
#' @param y A numeric vector of y-values at each x (same length as x).
#' @param xout A numeric vector of points at which to interpolate.
#'
#' @return A numeric vector of interpolated y-values at each point in `xout`.
#'
#' @details The function performs cubic spline interpolation using a tridiagonal
#' system to solve for the spline coefficients. If `xout` values fall outside
#' the `x` range, the function uses linear extrapolation, mirror R's `splinefun`
#' with `method = "natural"`
#'
#' @examples
#'   x <- c(0, 1, 2, 3, 4)
#'   y <- c(0, 1, 0, 1, 0)
#'   xout <- seq(0, 4, by = 0.1)
#'   natural_spline_interp(x, y, xout)
#' @export
NULL

natural_spline_interp <- function(x, y, xout) {
    .Call(`_BrainGnomes_natural_spline_interp`, x, y, xout)
}

